version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mongo:latest

    steps:
      - checkout
      - run:
          name: wait for postgres
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run: make
      - run: go test ./...
